---
stages:
- name: Build Java Projects
  inputs:
  - type: git
    branch: BUILD
    service: "test-devops-clone"
  triggers:
  - type: commit
  jobs:
  - name: Build Java
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
        #!/bin/bash
        echo "test"
