---
stages:
- name: Build Java Projects
  inputs:
  - type: git
    branch: ${BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: DOCKER_DIR
    value: ${DOCKER_DIR}
    type: text
  - name: BUILD_TARGET
    value: ${BUILD_TARGET}
    type: text
  jobs:
  - name: Build Java
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
        #!/bin/bash
        echo "Run gradle build..."
        export JAVA_HOME=~/java8
        export PATH=$JAVA_HOME/bin:$PATH
        /bin/bash build-microservice.sh
        cp ${BUILD_TARGET} ${DOCKER_DIR}/app.jar
        ls -al $PWD
        echo "Gradle build complete."
        
- name: Build Docker Image
  inputs:
  - type: job
    stage: Build Java Projects
    job: Build Java
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: LABEL_PREFIX
    value: ${LABEL_PREFIX}
    type: text
  - name: DOCKER_DIR
    value: ${DOCKER_DIR}
    type: text
  - name: REGION
    value: ${REGION}
    type: text
  - name: ORG
    value: ${ORG}
    type: text
  - name: SPACE
    value: ${SPACE}
    type: text
  - name: NAME
    value: ${NAME}
    type: text
  jobs:
  - name: Build container
    type: builder
    extension_id: ibm.devops.services.pipeline.container.builder
    target:
      region_id: ${REGION}
      organization: ${ORG}
      space: ${SPACE}
    IMAGE_NAME: ${NAME}
    USE_CACHED_LAYERS: 'true'
    COMMAND: |-
      #!/bin/bash
