---
stages:
- name: Build Java Projects
  inputs:
  - type: git
    branch: ${BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: DOCKER_DIR
    value: ${DOCKER_DIR}
    type: text
  - name: BUILD_TARGET
    value: ${BUILD_TARGET}
    type: text
  jobs:
  - name: Build Java
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
        #!/bin/bash
        echo "Run gradle build..."
        export JAVA_HOME=~/java8
        export PATH=$JAVA_HOME/bin:$PATH
        /bin/bash build-microservice.sh
        cp ${BUILD_TARGET} ${DOCKER_DIR}/app.jar
        ls -al $PWD
        echo "Gradle build complete."
