---
stages:
- name: Build Java Projects
  inputs:
  - url: https://github.com/ibm-cloud-architecture/refarch-cloudnative-netflix-eureka.git
    type: git
    branch: BUILD
    dir_name: null
  triggers:
  - type: manual
  jobs:
  - name: Build Java
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
        #!/bin/bash

        echo "test"
