---
stages:
- name: Build Java Projects
  inputs:
  - services: ${REPO}
    type: git
    branch: BUILD
  triggers:
  - type: commit
  jobs:
  - name: Build Java
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
        #!/bin/bash

        echo "test"
